### ISSUE TITLE
Server crashes: "Cannot switch to old mode now."

### ISSUE THREAD

**Issue by ksmyth** [nodejitsu/module-foundry#25]
```
node bin\module-foundry -c config\config.windows.json
LISTENING

_stream_readable.js:748
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:748:11)
    at IncomingMessage.Readable.resume (_stream_readable.js:733:3)
    at Router.dispatch (C:\Users\kevin\Documents\module-foundry\node_modules\director\lib\director\http\index.js:192:11)
    at handleAuthorized (C:\Users\kevin\Documents\module-foundry\lib\plugins\http.js:93:34)
    at finish (C:\Users\kevin\Documents\module-foundry\node_modules\understudy\lib\index.js:80:14)
    at iterate (C:\Users\kevin\Documents\module-foundry\node_modules\understudy\lib\index.js:50:13)
    at perform (C:\Users\kevin\Documents\module-foundry\node_modules\understudy\lib\index.js:83:3)
    at routeAuthorization (C:\Users\kevin\Documents\module-foundry\lib\plugins\http.js:70:13)
    at finish (C:\Users\kevin\Documents\module-foundry\node_modules\understudy\lib\index.js:80:14)
    at iterate (C:\Users\kevin\Documents\module-foundry\node_modules\understudy\lib\index.js:50:13)
```

To repro:

```
node --version
v0.10.33
git clone https://github.com/nodejitsu/module-foundry.git
git rev-parse HEAD
a1c0821f80f87a6719c961d28beb48589e3875ee
npm install --production
merge-recursive@0.0.3 node_modules\merge-recursive

buffered@0.0.1 node_modules\buffered

rimraf@2.2.8 node_modules\rimraf

understudy@1.1.0 node_modules\understudy

tmp@0.0.24 node_modules\tmp

async@0.9.0 node_modules\async

semver@4.1.1 node_modules\semver

director@1.2.7 node_modules\director

optimist@0.6.1 node_modules\optimist
├── wordwrap@0.0.2
└── minimist@0.0.10

request@2.51.0 node_modules\request
├── caseless@0.8.0
├── json-stringify-safe@5.0.0
├── forever-agent@0.5.2
├── aws-sign2@0.5.0
├── stringstream@0.0.4
├── oauth-sign@0.5.0
├── tunnel-agent@0.4.0
├── node-uuid@1.4.2
├── qs@2.3.3
├── mime-types@1.0.2
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── form-data@0.2.0 (mime-types@2.0.7)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
└── hawk@1.1.1 (cryptiles@0.2.2, sntp@0.2.4, boom@0.4.2, hoek@0.9.1)

module-smith@0.2.1 node_modules\module-smith
├── suspawn@0.1.1
├── uid-number@0.0.6
├── chownr@0.0.1
├── async@0.2.10
├── mkdirp@0.3.5
├── semver@2.2.1
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.7)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.5, mkdirp@0.5.0)
└── checkout@1.0.1 (ncp@0.2.7, request@2.27.0)

flatiron@0.4.3 node_modules\flatiron
├── optimist@0.6.0 (wordwrap@0.0.2, minimist@0.0.10)
├── broadway@0.3.6 (eventemitter2@0.4.14, utile@0.2.1, cliff@0.1.9, nconf@0.6.9, winston@0.8.0)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, utile@0.2.1, winston@0.8.3)

pkgcloud@0.8.17 node_modules\pkgcloud
├── url-join@0.0.1
├── qs@0.6.6
├── ip@0.0.5
├── eventemitter2@0.4.14
├── through@2.3.6
├── errs@0.2.4
├── filed@0.0.7
├── pkginfo@0.2.3
├── async@0.1.22
├── mime@1.2.11
├── underscore@1.4.4
├── utile@0.3.0 (deep-equal@0.2.1, async@0.9.0, ncp@1.0.1, i@0.3.2, mkdirp@0.5.0)
├── xml2js@0.1.14 (sax@0.6.1)
└── request@2.22.0 (json-stringify-safe@4.0.0, aws-sign@0.3.0, forever-agent@0.5.2, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, node-uuid@1.4.2, http-signature@0.10.1, form-data@0.0.8, hawk@0.13.1)

node bin\module-foundry -c config\config.windows.json
foundry-build --package example\packages\bcrypt.json --url http://localhost:1337
```

**Comment by ksmyth** [comment]
Any ideas?

**Comment by indexzero** [comment]
Has something to do with our streaming API.
